services:
  api:
      build: ./api
      restart: always
      container_name: api
      ports: 
          - 5000:5000
  frontend:
      build: ./frontend
      restart: always
      container_name: frontend
      ports:
          - 8080:80
      depends_on:
          - api